name: MacPowerGuard
options:
  bundleIdPrefix: com.macpowerguard
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"
    SDKROOT: macosx
    COMBINE_HIDPI_IMAGES: YES

targets:
  MacPowerGuard:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: MacPowerGuardSwift/Sources
      - path: MacPowerGuardSwift/Resources
    settings:
      base:
        PRODUCT_NAME: Mac Telemetry
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_MODULE_NAME: MacPowerGuard
        PRODUCT_BUNDLE_IDENTIFIER: com.macpowerguard.monitor
        INFOPLIST_FILE: MacPowerGuardSwift/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: MacPowerGuardSwift/MacPowerGuard.entitlements
        ENABLE_APP_SANDBOX: YES
        ENABLE_HARDENED_RUNTIME: YES
        LOCALIZATION_PREFERS_STRING_CATALOGS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_IDENTITY: Apple Development
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: BXAD9Q3TC8
    dependencies:
      - sdk: IOKit.framework

schemes:
  MacPowerGuard:
    build:
      targets:
        MacPowerGuard: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
